### PR TITLE
Roman Numerals Converter

### PR DESCRIPTION
**Pull request by Orzala-2024**
This is a Roman Numerals Converter created using HTML , CSS , and js .
My repo contains below files:
- index.html
- styles.css
- script.js 
- linters

Let's have a look to my project:
roman-converter

### CODE REVIEW

**Comment by Orzala-2024** [comment]
@Hamas2000,
Kindly view my project.

**Comment by Hamas2000** [comment]
Everything is correct. 
approved! 
well done!

**Comment by ahzamir** [comment]
@Orzala-2024 

- Why did you merge your pull request before your partner and your mentor's approval?

**Comment by Orzala-2024** [comment]
@ahzamir ,
My partner had problem with cloning my repo . she was not able to see any file in my feature branch which is (Roman). So I merged first pull request . Then all files appeared to her and I created another pull request to ask you and my partner to review my project.  But the second pull request is not yet merged.

**Comment by Orzala-2024** [comment]
@ahzamir ,
Kindly Check My Project.

**Comment by ahzamir** [comment]
> @ahzamir , My partner had problem with cloning my repo . she was not able to see any file in my feature branch which is (Roman). So I merged first pull request . Then all files appeared to her and I created another pull request to ask you and my partner to review my project. But the second pull request is not yet merged.

- Although you used the wrong approach for helping your partner review your project I will approve this pull request but never repeat this mistake again.
  - The main problem of files not showing up for your partner was that after she cloned your repo she needed to change the branch to feature cause after you clone a project normally it is in the development branch so it will not show the files so she needs to change the branch to feature. If you are faced with the same situation again instead of merging your branch help your partner to change her branch to feature.
  - By the way, a rule is a rule: Never merge before approval.

**Review by ahzamir — APPROVED** [review]
### Hi @Orzala-2024 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
